USE [LLSODTA]
GO
/****** Object:  StoredProcedure [dbo].[SP_GETHISTORY]    Script Date: 06/08/2012 12:08:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--EXEC SP_GETHISTORY '8100169'

ALTER PROCEDURE [dbo].[SP_GETHISTORY]
	@CONTRACT VARCHAR (10)
AS
BEGIN
	DECLARE @TODAY DATETIME
	DECLARE @MONTH INT
	DECLARE @YEAR  INT
	
	SET @TODAY = {FN NOW()}
	SET @MONTH = MONTH(@TODAY)
	SET @YEAR  = YEAR(@TODAY)
	
	IF (@MONTH - 1 = 0)
		BEGIN
			SET @MONTH = 12
			SET @YEAR  = @YEAR -1		
		END
	ELSE
		BEGIN
			SET @MONTH = @MONTH -1
		END
		
	DECLARE @DEA VARCHAR(10)	
	SELECT @DEA=CONDEA FROM HPMCON00 WHERE CONRUN=@CONTRACT
	
	
		select 
			a.CQMDNO,max(a.CQMETD) as CQSETD	
		from CQDM007 a 
		where a.CQMCSN=@CONTRACT
		group by a.CQMDNO,a.CQMETD 
		/*	
	
if object_id( 'tempdb..#M007_S003' ) is not  null drop table #M007_S003
	
	SELECT IDENTITY( int ) AS idcol,0 as CQMCHK,A.* ,B.*
	INTO #M007_S003
	FROM CQDM007 A
	LEFT JOIN CQDS003  B ON A.CQMDNO=B.CQSDNO
	LEFT JOIN HPMCON00 C ON B.CQSCSN=C.CONRUN
	WHERE 
	 (MONTH(A.CQMDTE)=@MONTH) 
	  AND (YEAR(A.CQMDTE)=@YEAR)
	 AND 
	  (C.CONDEA=@DEA)
	  AND (B.CQSRCT<>'O')
	ORDER BY B.CQSDNO,B.CQSCSN
	
	SELECT * FROM #M007_S003 ORDER BY idcol 	
	*/  

END
